# Generated by Django 4.2.8 on 2023-12-23 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_remove_category_image_remove_product_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='images',
            field=models.ImageField(null=True, upload_to='Category_Images'),
        ),
        migrations.AlterField(
            model_name='product',
            name='images',
            field=models.ImageField(null=True, upload_to='Product_Images'),
        ),
    ]
